networks:
  nginx_network:
    external: true

services:
  acesearch:
    networks:
      - nginx_network
    build: .
    container_name: acesearch
    restart: unless-stopped
    volumes:
      - /root/playlists:/app/playlists
